begin;
select plan(25);
select has_table('public','campaign_sources','campaign sources');
select has_table('public','automations','automations');
select has_table('public','automation_versions','immutable versions');
select has_table('public','automation_triggers','triggers');
select has_table('public','automation_questions','questions');
select has_table('public','automation_rules','rules');
select has_table('public','automation_message_steps','message steps');
select has_table('public','service_windows','service windows');
select has_table('public','automation_runs','runs');
select has_table('public','automation_run_steps','run steps');
select has_table('public','outbound_attempts','outbound attempts');
select has_table('public','automation_idempotency_keys','idempotency');
select has_table('public','automation_dead_letters','dead letters');
select has_table('public','human_takeovers','takeovers');
select has_table('public','automation_audit_events','audit');
select ok(relrowsecurity,'automation RLS') from pg_class where oid='public.automations'::regclass;
select ok(relforcerowsecurity,'automation forced RLS') from pg_class where oid='public.automations'::regclass;
select ok(relrowsecurity,'runs RLS') from pg_class where oid='public.automation_runs'::regclass;
select ok(relforcerowsecurity,'runs forced RLS') from pg_class where oid='public.automation_runs'::regclass;
select ok(relrowsecurity,'windows RLS') from pg_class where oid='public.service_windows'::regclass;
select ok(not has_table_privilege('authenticated','public.automations','INSERT'),'browser cannot create directly');
select ok(not has_table_privilege('authenticated','public.automation_runs','UPDATE'),'browser cannot invent transitions');
select ok(not has_table_privilege('authenticated','public.service_windows','INSERT'),'browser cannot open window');
select ok((select count(*)>0 from pg_indexes where schemaname='public' and tablename='outbound_attempts' and indexdef like '%workspace_id, idempotency_key%'),'send keys unique per workspace');
select col_is_pk('public','automation_runs','id','run primary key');
select * from finish();
rollback;
