begin;
select plan(15);
select has_table('public','business_profiles','business profile exists');
select has_table('public','business_faq_items','FAQ exists');
select has_table('public','business_price_items','prices exist');
select has_table('public','workspace_ai_credentials','credential envelopes exist');
select has_table('public','ai_execution_audit_events','AI audit exists');
select ok(relrowsecurity,'profile RLS') from pg_class where oid='public.business_profiles'::regclass;
select ok(relforcerowsecurity,'profile forced RLS') from pg_class where oid='public.business_profiles'::regclass;
select ok(relrowsecurity,'credential RLS') from pg_class where oid='public.workspace_ai_credentials'::regclass;
select ok(relforcerowsecurity,'credential forced RLS') from pg_class where oid='public.workspace_ai_credentials'::regclass;
select ok(not has_table_privilege('authenticated','public.workspace_ai_credentials','INSERT'),'browser cannot insert credentials');
select ok(not has_table_privilege('authenticated','public.workspace_ai_credentials','UPDATE'),'browser cannot update credentials');
select ok(not has_table_privilege('authenticated','public.workspace_ai_credentials','DELETE'),'browser cannot delete credentials');
select ok(has_column_privilege('authenticated','public.workspace_ai_credentials','masked_suffix','SELECT'),'browser can read masked suffix');
select ok(not has_column_privilege('authenticated','public.workspace_ai_credentials','ciphertext','SELECT'),'browser cannot read ciphertext');
select col_is_pk('public','business_profiles','workspace_id','one profile per workspace');
select * from finish();
rollback;
