begin;
select plan(16);
select has_table('public','meta_connections','connections exist');
select has_table('public','meta_webhook_events','webhook events exist');
select has_table('public','provider_event_outbox','outbox exists');
select has_table('public','meta_connection_audit_events','connection audit exists');
select ok(relrowsecurity,'connection RLS') from pg_class where oid='public.meta_connections'::regclass;
select ok(relforcerowsecurity,'connection forced RLS') from pg_class where oid='public.meta_connections'::regclass;
select ok(relrowsecurity,'webhook event RLS') from pg_class where oid='public.meta_webhook_events'::regclass;
select ok(relforcerowsecurity,'outbox forced RLS') from pg_class where oid='public.provider_event_outbox'::regclass;
select ok(not has_table_privilege('authenticated','public.meta_connections','INSERT'),'browser cannot insert connection');
select ok(not has_table_privilege('authenticated','public.meta_connections','UPDATE'),'browser cannot update connection');
select ok(not has_table_privilege('authenticated','public.meta_connections','DELETE'),'browser cannot delete connection');
select ok(not has_column_privilege('authenticated','public.meta_connections','token_ciphertext','SELECT'),'browser cannot read token ciphertext');
select ok(not has_column_privilege('authenticated','public.meta_connections','token_iv','SELECT'),'browser cannot read token IV');
select ok(has_column_privilege('authenticated','public.meta_connections','token_masked_suffix','SELECT'),'browser may read masked suffix');
select ok(not has_function_privilege('authenticated','public.ingest_meta_event(text,text,text,text,text,text,text,jsonb,jsonb,timestamptz)','EXECUTE'),'browser cannot ingest trusted webhooks');
select ok(has_function_privilege('service_role','public.ingest_meta_event(text,text,text,text,text,text,text,jsonb,jsonb,timestamptz)','EXECUTE'),'service role may ingest verified webhooks');
select * from finish();
rollback;
