import type { Result } from "@/src/lib/result";
import type { BillingActionAuthorization } from "./live-billing-gate";

export type BillingProviderName = "fake" | "paytr";

export type SubscriptionStatus = "incomplete" | "trialing" | "active" | "past_due" | "canceled";

export type BillingStatus = Readonly<{
  status: SubscriptionStatus;
  planDisplayName: string;
  priceMinorUnits: number;
  currency: string;
  trialEndsAt: string | null;
  trialDaysLeft: number | null;
  currentPeriodEndsAt: string | null;
  canceledAt: string | null;
  paymentMethod: Readonly<{
    provider: BillingProviderName;
    maskedCardSuffix: string;
    cardBrand: string | null;
  }> | null;
}>;

export type CardRegistrationResult = Readonly<{
  providerCustomerRef: string;
  providerCardRef: string;
  cardBrand?: string;
  maskedCardSuffix: string;
  /** Raw value to HMAC for trial-fingerprint dedupe; for PayTR this is the ctoken. */
  cardFingerprintSource: string;
}>;

export type ChargeOutcome = Readonly<{
  status: "succeeded" | "declined" | "unknown";
  providerTransactionRef?: string;
  failureCode?: string;
}>;

export type VerifiedBillingWebhookEvent = Readonly<{
  eventRef: string;
  eventType: string;
  chargeAttemptId: string;
  safePayload: Record<string, unknown>;
}>;

/**
 * Whether the browser redirect back from the provider's hosted card page may
 * be treated as proof that a card was actually stored.
 *
 * `authoritative` is only correct for a closed local loop (the fake provider),
 * where the "redirect" is generated by this process and never leaves it.
 *
 * `requires_provider_confirmation` means the redirect is attacker-controllable
 * — the user's browser can be pointed at the callback with any query string —
 * so the card and any entitlement it unlocks must come from a separately
 * authenticated server-to-server notification instead. Same rule as the Meta
 * OAuth callback, which accepts only a `code` it then exchanges server-side
 * (app/api/connections/meta/callback/route.ts).
 */
export type CallbackAuthority = "authoritative" | "requires_provider_confirmation";

export interface PaymentProvider {
  readonly providerName: BillingProviderName;
  readonly callbackAuthority: CallbackAuthority;

  initCardRegistration(
    input: Readonly<{
      workspaceId: string;
      returnUrl: string;
      customerRef: string;
      customerEmail: string;
      userIp: string;
      authorization: BillingActionAuthorization;
    }>
  ): Promise<Result<{ redirectUrl: string; providerSessionRef: string }>>;

  verifyCardRegistrationCallback(
    input: Readonly<{
      rawBody: Uint8Array;
      query: Readonly<Record<string, string>>;
    }>
  ): Promise<Result<CardRegistrationResult>>;

  chargeStoredCard(
    input: Readonly<{
      providerCustomerRef: string;
      providerCardRef: string;
      amountMinorUnits: number;
      currency: "TRY";
      orderRef: string;
      customerEmail: string;
      userIp: string;
      authorization: BillingActionAuthorization;
    }>
  ): Promise<Result<ChargeOutcome>>;

  verifyAndParseWebhook(
    input: Readonly<{
      rawBody: Uint8Array;
      headers: Readonly<Record<string, string>>;
    }>
  ): Result<VerifiedBillingWebhookEvent>;
}
